### PR TITLE
Added DeFi section introduction

### PR DESCRIPTION
**Pull request by HilliamT**
Themes brought up:

- What finance does
- TradFi vs DeFi: custody
- Tokens + examples
- Composability

### CODE REVIEW

**Comment by dcbuild3r** [comment]
Hey, I can't accept this pull request as there's more people working on this section at the moment. In the next couple of days I'll create coordination channels.

**Comment by HilliamT** [comment]
Sounds good! Couldn't find anything on any forks, but happy to collaborate on that section with people

**Comment by dcbuild3r** [comment]
Let's get a telegram group for active contributors, after some time I'll create a discord/forum structure. For the DeFi section hit up @amadeobrands

**Comment by dcbuild3r** [comment]
I'll get started with a provisional version of the defi-development section which will be inspired from these two links:

- [defi-learning](https://defi-learning.org/)
- [defi-developer-roadmap](https://github.com/OffcierCia/DeFi-Developer-Road-Map)

**Pull request closed without merging**
